### ISSUE TITLE
HXML file should not be required

### ISSUE THREAD

**Issue by Gama11** [ncannasse/hashlink-debugger#4]
The requirement for a HXML is annoying, there's several scenarios in which you might not have one:

- you could have all compiler arguments defined in `tasks.json`
- you're using a third-party build tool which doesn't use HXML files, or only generates them for builds (for instance Lime is planning to add HL support in the future https://github.com/openfl/lime/issues/1060)

Or even if you have one, it might not contain `-hl` (for instance because `-hl` is appended by a task) in which case the adapter complains as well:

```
ERROR : build.hxml file does not contain -hl output
```

Why is it necessary, just to find out the program path? There should be a `program` property in the launch config for that instead.

**Comment by ncannasse** [comment]
We need both the `.hl` file and the whole class path to resolve files from their classpath-relative-path to the local computer absolute-path. It is necessary not to store absolute paths because you might debug on a different computer the application was compiled on (attaching to a process for instance).

**Comment by ncannasse** [comment]
I have made the HXML mandatory for now.

**Comment by Gama11** [comment]
We could probably add an API to vshaxe to retrieve the compiler arguments / the classpath? It already has an extension API. I really don't like this HXML requirement...

**Comment by Gama11** [comment]
Note that that wouldn't be 100% fool-proof, it relies on the correct display configuration being selected at the time you start debugging.

**Comment by ncannasse** [comment]
I'm open to suggestions

**Comment by Gama11** [comment]
The debug extension would need to add vshaxe as a dependency, then it could access its API like so:

```haxe
var vshaxe:Vshaxe = Vscode.extensions.getExtension("nadako.vshaxe").exports
```

We could add something like this to [Vshaxe](https://github.com/vshaxe/vshaxe/blob/master/src-api/Vshaxe.hx):

```haxe
var onDidChangeDisplayArguments(get,never):Event<Array<String>>;
```

or maybe:

```haxe
var displayArguments(default,never):ReadOnlyArray<String>;
```

Depending on whether an event with a callback is helpful or not. The debug extension would then need to pass that on to the debug adapter, but that should be possible.

What do you think @nadako?

**Comment by nadako** [comment]
Sure, can be useful for extensions like debug adapters.

I feel like at some point we'll have to come up with a proper "compilation configuration" structure instead of just argument array being parsed by every extension in their own way, but let's save that for the future.

**Comment by nadako** [comment]
Well, it's still "display arguments" in the first place, so I don't know. At the start I wanted to be very specific with that, because random hxml wouldn't work for display and I didn't want people to get confused with that. But maybe at this point we should indeed redesign the whole "build configuration" thing. I actually thought about that a year ago: https://github.com/nadako/hxproject, maybe it's a good time to revive that experiment.

Regarding the extension identifier, I'm not against it, but in the past there was no way to change it without publishing it as a new extension, meaning that we lose stars/download counts, etc. IIRC it's still the case today, but gotta check that.

**Comment by Gama11** [comment]
Yeah, losing those stats wouldn't be acceptable, not to mention that people wouldn't get updates if they have installed the old extension...

We actually also already had a vshaxe account for the marketplace, which I used for the Haxe Debug extension and the Haxe Extension Pack. :P

https://marketplace.visualstudio.com/search?term=publisher%3A%22vshaxe%22&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by ncannasse** [comment]
Yes I agree it's not good to lose all history. 

@Gama11 ah you're the one publishing "Haxe Debug" :) I was thinking it would be nice to rename it + change its icon so it's "Haxe Flash Debugger" since it's quite misleading atm. Unless you have more plans for it ?

**Comment by Gama11** [comment]
Yes, the original plan was to have all debuggers in there.. It also has experimental HXCPP support on the dev branch that was never published.

**Comment by Gama11** [comment]
Ok, retrieving classpaths would be a bit higher-level than a `displayArguments` API, but there's quite some overlap with the code we have for the dependency explorer (which also parses HXML, resolves paths of haxelibs etc). Makes sense to me.

**Comment by ncannasse** [comment]
Ok good, I'll open an issue on vshaxe then, and wait until it's published on marketplace to make the changes in hl

**Comment by ibilon** [comment]
> Actually given the code for building the final classpath is a bit complex (see https://github.com/ncannasse/vscode_hl/blob/master/src/HLAdapter.hx#L104)

That doesn't take into account the classpaths added by init macro.

Or the changes to the hxml between compiling and debugging. It would be a lot better and safer to include this information in the program itself.

**Comment by Gama11** [comment]
@ncannasse has explained earlier in this issue why he doesn't like that approach:

>We need both the .hl file and the whole class path to resolve files from their classpath-relative-path to the local computer absolute-path. It is necessary not to store absolute paths because you might debug on a different computer the application was compiled on (attaching to a process for instance).

I can see the arguments for both.. Perhaps a hybrid approach could work?

- store both a relative and an absolute component for each path
- obtain the absolute path by pre-fixing the absolute component to the relative one, if the file exists, use it
- otherwise, try to find the file through the classpath with the relative component

That way, it would be more robust to changed classpaths (classpaths could be optional entirely), as long as you're on the same machine, but still work when debugging a binary compiled elsewhere.

**Comment by ncannasse** [comment]
I don't want to store full paths in .hl output, it's ugly in stack traces and cause other issues (conflicts while otherwise there was no changes). I don't want to change the whole runtime by having two paths (relative and absolute) as that would be a mess.

We could create a separate file that stores the classpath the .hl file was compiled with but that seems overkill to have all these small files lying around. Also I don't think in general that's a good idea to modify the class path by init macros, as this creates some issues with compiler cache.

**Comment by ibilon** [comment]
> Also I don't think in general that's a good idea to modify the class path by init macros

I also agree, but that's the only solution for libraries since the content of extraParams.hxml is not relative to it, making `-resource` and `-cp` useless unless you use an init macro to add them.
But that's an other issue.

**Comment by ncannasse** [comment]
If it's just for reousrces then it will not affect debugger ;) and I don't
think that's a good idea to have additional -cp in extraParams.hxml, do you
have examples on why this would be necessary?

On Tue, Apr 10, 2018 at 11:43 AM, Valentin Lemière <notifications@github.com

**Comment by ibilon** [comment]
You can only have one in haxelib.json, so in the rare case you need two.
If you have git submodules for instance.

**Comment by Gama11** [comment]
jstack is an example for a library that uses `addClassPath()`, it uses it to conditionalize the path based on the target:

https://github.com/RealyUniqueName/JStack/blob/0c43ba383ee9c4ef49196186d3f2f877a2b89bb8/src/jstack/Tools.hx#L32-L36

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/hashlink-debugger/issues/4.
