### ISSUE TITLE
cwd property should be optional

### ISSUE THREAD

**Issue by Gama11** [ncannasse/hashlink-debugger#5]
Considering that it will be `"cwd": "${workspaceRoot}"` in 90% of cases, it would be nice if it was optional. There's a discussion on `cwd` for debug adapters here, `startSessionCommand` is given as the solution:

https://github.com/Microsoft/vscode/issues/7435#issuecomment-292167323

However, it looks like `startSessionCommand` has been replaced with something else by now:

https://github.com/Microsoft/vscode/issues/33795

Otherwise, `cwd`  should be marked as a required field to avoid this error:

![](https://i.imgur.com/Kj45ihw.png)

**Comment by ncannasse** [comment]
It is marked as required now, I'll investigate alternative solution.

**Comment by Gama11** [comment]
Requiring a `program` property might make this issue obsolete as well (and the hxml wouldn't need a `-hl` flag anymore)? As you can see here, it's required for all other targets:

https://github.com/Gama11/HaxeRepro/blob/master/.vscode/launch.json

**Comment by Gama11** [comment]
Moved to https://github.com/vshaxe/hashlink-debugger/issues/3.
